version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: bookstore
    env_file:
      - .env
    networks:
      - bookstore-net

  db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookstore
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bookstore-net
    user: "1000:1000"

networks:
  bookstore-net:
    driver: bridge

volumes:
  db_data:
    driver: local